  
type Bookmark {
  id: ID!
  title: String!
  desc: String!
  url: String!
}

type Query {
  listBookmark: [Bookmark]
}

type Mutation {
  createBookmark( id: ID! title: String! desc: String! url: String!): String!
  deleteBookmark(id: ID!): String!
}